name: Slack Notification

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "channel": "kangs",
              "text": "New pull request opened by ${{ github.event.pull_request.user.login }}", 
              "blocks":[
                 {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.event.pull_request.html_url }} \nReviewers:${{ steps.reviewers.outputs.reviewers }}"
                }
              }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
